#!/bin/bash

# OmniGuard Setup Script

echo "🌍 Welcome to OmniGuard Setup!"
echo "------------------------------"

ENV_FILE=".env"

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  A $ENV_FILE file already exists."
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Existing configuration preserved."
        exit 0
    fi
fi

echo "Please enter your Google Gemini API Key."
echo "If you don't have one, get it here: https://aistudio.google.com/app/apikey"
read -p "Gemini API Key: " GEMINI_KEY

if [ -z "$GEMINI_KEY" ]; then
    echo "❌ Error: Gemini API Key cannot be empty."
    exit 1
fi

# Default Postgres credentials
POSTGRES_USER="omniguard_user"
POSTGRES_PASSWORD="omniguard_password"
POSTGRES_DB="omniguard_db"

echo "Creating $ENV_FILE..."

cat <<EOF > "$ENV_FILE"
# OmniGuard Environment Variables
# Generated by setup.sh

# Google Gemini API Key
GEMINI_KEY=$GEMINI_KEY

# PostgreSQL Configuration
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

# Optional: Location defaults (Cairo)
MY_LAT=30.0444
MY_LON=31.2357
EOF

echo "✅ $ENV_FILE created successfully!"
echo ""
echo "You can now run the system with:"
echo "  docker compose up --build -d"
echo ""
echo "Happy monitoring! 🚀"
